[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.7.0"
edition = "2024"
rust-version = "1.92"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sagikazarmark/email-rs"
homepage = "https://email-rs.dev"
keywords = ["email", "smtp", "mail", "async", "mailer"]
categories = ["email", "network-programming", "asynchronous"]

[workspace.dependencies]
email-attachment = { path = "crates/email-attachment", version = "0.7.0", default-features = false }
email-attachment-opendal = { path = "crates/email-attachment-opendal", version = "0.7.0", default-features = false }
email-kit = { path = "crates/email-kit", version = "0.7.0", default-features = false }
email-message = { path = "crates/email-message", version = "0.7.0", default-features = false }
email-message-wire = { path = "crates/email-message-wire", version = "0.7.0", default-features = false }
email-transport = { path = "crates/email-transport", version = "0.7.0", default-features = false }
email-transport-lettre = { path = "crates/email-transport-lettre", version = "0.7.0", default-features = false }
email-transport-resend = { path = "crates/email-transport-resend", version = "0.7.0", default-features = false }
email-transport-test = { path = "crates/email-transport-test", default-features = false }
restate-email = { path = "crates/restate-email", version = "0.7.0", default-features = false }

erased-serde = "0.4"
futures-util = "0.3"
opendal = { version = "0.58.2", default-features = false }
proptest = "1"
reqwest = { version = "0.13", default-features = false }
restate-sdk = "0.11"
schemars = "1.2"
serde = "1"
serde_json = "1"
serde_path_to_error = "0.1"
thiserror = "2"
time = { version = "0.3", default-features = false }
tokio = "1"

[workspace.metadata.release]
sign-commit = true
sign-tag = true
shared-version = true
tag-message = "Release {{version}}"
tag-name = "v{{version}}"
