ignore = [".devenv", "target"]

[modules.email]
source = "."
entrypoint = true

settings.rustVersion = "1.98-slim-trixie"

[modules.rust]
source = "github.com/sagikazarmark/daggerverse-beta/rust"

settings.version = "1.98-slim-trixie"

[modules.dagger-gha]
source = "github.com/sagikazarmark/daggerverse-beta/dagger-gha"
