name = "email"
engineVersion = "v1.0.0"
runtime.source = "dang"
include = ["!.devenv", "!target"]

[[dependencies]]
name = "hurl"
source = "github.com/sagikazarmark/daggerverse-beta/hurl"

[[dependencies]]
name = "restate"
source = "github.com/sagikazarmark/daggerverse-beta/restate"

[[dependencies]]
name = "rust"
source = "github.com/sagikazarmark/daggerverse-beta/rust"
