[package]
name = "email-attachment-opendal"
version = { workspace = true }
description = "OpenDAL attachment resolver for email-rs"
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
keywords = ["email", "attachment", "storage", "opendal"]
categories = ["email", "filesystem"]

[features]
default = ["opendal/default"]
services-azblob = ["opendal/services-azblob"]
services-fs = ["opendal/services-fs"]
services-gcs = ["opendal/services-gcs"]
services-http = ["opendal/services-http"]
services-memory = ["opendal/services-memory"]
services-s3 = ["opendal/services-s3"]

[dependencies]
email-attachment = { workspace = true }
email-message = { workspace = true }
opendal = { workspace = true }

futures-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
