[package]
name = "email-message-fuzz"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "address_list_from_str"
path = "fuzz_targets/address_list_from_str.rs"
test = false
doc = false
bench = false

[dependencies]
email-message = { path = "..", features = ["arbitrary"] }

libfuzzer-sys = "0.4"

[package.metadata]
cargo-fuzz = true

[workspace]
