name = "end-to-end"
engineVersion = "v1.0.0"
runtime.source = "dang"

[[dependencies]]
name = "hurl"
source = "../hurl"

[[dependencies]]
name = "restate"
source = "../restate"

[[dependencies]]
name = "rust"
source = "github.com/sagikazarmark/daggerverse-beta/rust"
